# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61gent_service.proto\x12\x0emistralPackage\"M\n\x11\x41gentQueryRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x17\n\x0f\x61gentIdentifier\x18\x02 \x01(\t\x12\x13\n\x0bqueryString\x18\x03 \x01(\t\"\x87\x01\n\x11ModelQueryRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x17\n\x0fmodelIdentifier\x18\x02 \x01(\t\x12\x13\n\x0bqueryString\x18\x03 \x01(\t\x12\x15\n\rsystemMessage\x18\x04 \x01(\t\x12\x0c\n\x04role\x18\x05 \x01(\t\x12\x13\n\x0btemperature\x18\x06 \x01(\x02\"E\n\rQueryResponse\x12\x11\n\trequestId\x18\x01 \x01(\x05\x12\x10\n\x08response\x18\x02 \x01(\t\x12\x0f\n\x07runTime\x18\x03 \x01(\x05\x32\xae\x01\n\x0c\x41gentService\x12N\n\nqueryAgent\x12!.mistralPackage.AgentQueryRequest\x1a\x1d.mistralPackage.QueryResponse\x12N\n\nqueryModel\x12!.mistralPackage.ModelQueryRequest\x1a\x1d.mistralPackage.QueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTQUERYREQUEST']._serialized_start=39
  _globals['_AGENTQUERYREQUEST']._serialized_end=116
  _globals['_MODELQUERYREQUEST']._serialized_start=119
  _globals['_MODELQUERYREQUEST']._serialized_end=254
  _globals['_QUERYRESPONSE']._serialized_start=256
  _globals['_QUERYRESPONSE']._serialized_end=325
  _globals['_AGENTSERVICE']._serialized_start=328
  _globals['_AGENTSERVICE']._serialized_end=502
# @@protoc_insertion_point(module_scope)
