# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serve_mistral.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13serve_mistral.proto\x12\x0emistralPackage\"H\n\x0cQueryRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x17\n\x0fmodelIdentifier\x18\x02 \x01(\t\x12\x13\n\x0bqueryString\x18\x03 \x01(\t\"E\n\rQueryResponse\x12\x11\n\trequestId\x18\x01 \x01(\x05\x12\x10\n\x08response\x18\x02 \x01(\t\x12\x0f\n\x07runTime\x18\x03 \x01(\x05\x32W\n\nLlmService\x12I\n\nqueryModel\x12\x1c.mistralPackage.QueryRequest\x1a\x1d.mistralPackage.QueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serve_mistral_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQUEST']._serialized_start=39
  _globals['_QUERYREQUEST']._serialized_end=111
  _globals['_QUERYRESPONSE']._serialized_start=113
  _globals['_QUERYRESPONSE']._serialized_end=182
  _globals['_LLMSERVICE']._serialized_start=184
  _globals['_LLMSERVICE']._serialized_end=271
# @@protoc_insertion_point(module_scope)
